version: '3.8'

services:
  database:
    image: postgres:13.4
    container_name: odyssey-database
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - odyssey-network
    logging:
      driver: journald
    expose:
      - '${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: ghcr.io/0dy553y/odyssey-backend:latest
    container_name: odyssey-backend
    restart: always
    depends_on:
      - database
    networks:
      - odyssey-network
    logging:
      driver: journald
    expose:
      - '8001'
    environment:
      RAILS_ENV: production
      PORT: 8001
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_HOSTNAME: odyssey-database
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: disable

  frontend:
    image: ghcr.io/0dy553y/odyssey-frontend:latest
    container_name: odyssey-frontend
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend
    networks:
      - odyssey-network
    logging:
      driver: journald
    ports:
      - '80:80'
      - '443:443'
    environment:
      BASE_SERVER_URL: ${BASE_SERVER_URL}

  certbot:
    image: certbot/certbot
    container_name: odyssey-certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - odyssey-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  odyssey-network
